### ISSUE TITLE
loss 调整参数问题。

### ISSUE THREAD

**Issue by wangwentaodeheimaojingzhang** [gehaocool/CombinedMargin-caffe#10]
请问您对于这个loss有什么m1,m2,m3,s这个几个有什么调参心得吗？怎么样才能找到一个适合自己数据集的参数呢。感谢！！！！

**Comment by gehaocool** [comment]
根据m1, m2, m3的含义，可以大致推算一个较理想的范围，但是这个范围还是相当大，具体哪一组参数组合效果更好，很多时候只能分别训练模型进行比较了。
而对超参数进行选择的过程其实是一个很复杂的事情，我也没有太多心得，个人感觉可以从粗到精，先大范围选一些，再从效果较好的参数组合附近做微调。
也就是说，针对不同的数据集，其实你可以从已经在之前数据集上试验过并且效果较好的超参数集合开始调整你的超参数。
比如m1, m2, m3的值，insightface已经做过若干组实验，认为1, 0.3, 0.2效果最好，而s的值是64比较好（这一点在CosineFace里也有提到），那么完全可以在这些值的附近做微调进行多组实验。
或者像Andrew Ng的课里提到的方法，随机选择若干超参数组合，分别实验。
