### ISSUE TITLE
关于loss的梯度计算

### ISSUE THREAD

**Issue by wuruijie123** [gehaocool/CombinedMargin-caffe#16]
作者你好，有一个关于loss的梯度计算的问题想请假一下：
combined margin的梯度我看你的代码是：m1 * pow(1 - pow(cos_theta, 2), -0.5)  * sin(m1_mul_theta_plus_m2)，其实就是m1 * sin(m1_theta+m2) * sin(theta)，我自己的计算是：-m1 * sin(m1 * theta+m2)，请问你的计算是怎么得到的呢？万分感谢！

**Comment by gehaocool** [comment]
f=cos(m1*arccos(cos(theta_j))+m2)-m3
对输入值x=cos(theta_j)求导
也就是f=cos(m1*arccos(x)+m2)-m3对x求导
分步求导最后要乘以y=arccos(x)的导数y'=-1/sqrt(1-x^2)，也就是pow(1 - pow(cos_theta, 2), -0.5)
另一项sin(m1_mul_theta_plus_m2)就是sin(m1*theta_j+m2)-m3，两项都有负号抵消了
翻出来一张之前的笔记，仅供参考
![image](https://user-images.githubusercontent.com/6713571/52837496-ec562700-3129-11e9-97bb-12b5c293c320.png)

**Comment by wuruijie123** [comment]
非常感谢作者的回复，原来我一直以为是损失函数对theta导数，原来是对cos(theta)的导数，只不过是对theta做了变换，使得训练变得困难，从而迫使theta能训练到一个更低的值，使得同类直接距离拉近了。

**Comment by gehaocool** [comment]
@wuruijie123 caffe的梯度实现是这样的，原理就是反向传播的链式法则
