### ISSUE TITLE
关于网络参数及数据标签的疑问

### ISSUE THREAD

**Issue by zhDai** [gehaocool/CombinedMargin-caffe#19]
你好，我可以问下你在训练的时候，输入的图片形式是怎么样的（看的是/res36-training-config/CombinedMargin_spherenet36_E_model.prototxt）
layer {
  name: "data"
  type: "ImageData"
  top: "data"
  top: "label"
  transform_param {
    mean_value: 127.5
    mean_value: 127.5
    mean_value: 127.5
    scale: 0.0078125
    mirror: true
    contrast_brightness_adjustment: true
	  min_contrast: 0.8
	  max_contrast: 1.2
	  max_color_shift: 20
	  smooth_filtering: true
	  max_smooth: 6
	  apply_probability: 0.5
  }
  image_data_param {
    root_folder: "/media/deep/t5/trillionpairs/aligned-112X96/"
    source: "data/train_list.txt"
    batch_size: 128
    rand_skip: 10000
    shuffle: true
  }
}
train_list.txt这个文件可以截图一些看看什么形式么。
**********************************************************************
layer {
  name: "fc6_l2"
  type: "InnerProduct"
  bottom: "norm1"
  top: "fc6"
  param {
    lr_mult: 1
  }
  inner_product_param{
    num_output: 180855
    normalize: true
    weight_filler {
      type: "xavier"
    }
    bias_term: false
  }
}
这个num_output是怎么设定的
**********************************************************************
layer {
  name: "fc6_margin_scale"
  type: "Scale"
  bottom: "fc6_margin"
  top: "fc6_margin_scale"
  param {
    lr_mult: 0
    decay_mult: 0
  }
  scale_param {
    filler{
      type: "constant"
      value: 64
    }
  }
}
这个value64是怎么设定的
*************************************************************************
谢谢~

**Comment by gehaocool** [comment]
1. 第一个问题，关于train_list.txt的格式。这个就是训练数据的标注信息，也就是label。
具体格式就是每一行有两个值，第一个值是人脸图片的路径（绝对路径或者相对路径配合root_folder这个参数）；第二个值就是一个label，为非负整数值，表示这张图片的人的身份id，区分不同的人。
同一个人的多张图片，就分为多行，自然而然的这些行的图片路径不同，但表示身份id的label是相同的。
截图作为例子：
![image](https://user-images.githubusercontent.com/6713571/54573972-6cbdbf80-4a29-11e9-9ba8-5f1dd0e9aa95.png)

2. num_output就是训练数据中所有的不同的身份id数，**注意**：问题1中提到的label值可以是不连续的，也就是可以从中跳过某些值的，所以要具体计算数量。如果这个num_output和label总数不符合，会报错。

3. value 64是一个超参数，表示经过归一化后的特征再进行scale的尺度。CosineFace那篇文章里做了对比实验来确认这个值，给出的结论64是比较好的取值。

**Comment by zhDai** [comment]
好的，谢谢~~~也就是说arcface也是这样的形式么。这其实是个分类网络，我一直以为训练方式是一对人脸及他们的标签（就0,1标签。0是同一个人，1是不同的人）来训练。

**Comment by gehaocool** [comment]
是的，arcface也是类似的形式
训练的流程是和分类任务很类似的
