### ISSUE TITLE
InnerProduct why you write here？

### ISSUE THREAD

**Issue by sunjunlishi** [gehaocool/CombinedMargin-caffe#2]
InnerProduct already exists. Why do you write it ？is it differently?

**Comment by gehaocool** [comment]
in this version, we normalize the output of InnerProduct layer.
you can follow the simple instruction in [toadd.proto](https://github.com/gehaocool/CombinedMargin-caffe/blob/master/toadd.proto)
this version of InnerProduct layer was implemented by happynear in [AMSoftmax](https://github.com/happynear/AMSoftmax)

**Comment by sunjunlishi** [comment]
谢谢thanks
