### ISSUE TITLE
数据预处理的一个小疑问

### ISSUE THREAD

**Issue by zhDai** [gehaocool/CombinedMargin-caffe#21]
您好，我注意到glin的数据虽然都是对齐的，但是不是一个crop后的人脸数据，是否还需要把脸抠出来再去做训练？还是说不需要做crop操作，直接就把对齐后的图片加载进去就好了。

**Comment by gehaocool** [comment]
还是需要crop出来的
具体的过程是这样的，glint给出了一张大图片中人脸的5个特征点的坐标，首先利用这些特征点坐标对齐到平均脸上去，这个过程需要进行仿射变换，然后从对齐后（也就是变换后）的图片中crop出人脸部分，并且resize到特定的尺寸（比如112×112或者112×96），这个图片才是用于训练的人脸图片

**Comment by zhDai** [comment]
glin的数据蛮大的。蛮耗时~~谢谢
