### ISSUE TITLE
关键词：mobilenet，margin设置

### ISSUE THREAD

**Issue by zhDai** [gehaocool/CombinedMargin-caffe#22]
你好，我想用mobilenet去提取特征，但是loss想用margin loss~用你之前的3个margin值去训练，是不是不合适了。

**Comment by gehaocool** [comment]
我觉得应该也是可以的
但还是建议你用0.3, 0.2这组值作为baseline，从这一点出发搜索其他超参数组合是否能取得更好的效果
另外个人认为训练数据的不同，会影响margin这一超参数的选择
