### ISSUE TITLE
How can i use your caffemodel in opencv. I have tried it but got similarity almost all 98%

### ISSUE THREAD

**Issue by JiageWang** [gehaocool/CombinedMargin-caffe#23]

**Comment by gehaocool** [comment]
What do you mean 'use in opencv'?
Do you align all the test images?

**Comment by gehaocool** [comment]
@JiageWang 
you may refer to this issue #18

**Comment by JiageWang** [comment]
> @JiageWang
> you may refer to this issue #18

**Comment by JiageWang** [comment]
> @JiageWang
> you may refer to this issue #18

oh,thanks for your attention, I will try it.
