### ISSUE TITLE
请问您是怎么制作您的ResNet-36的deploy.caffemodel呢?

### ISSUE THREAD

**Issue by Gincoeng** [gehaocool/CombinedMargin-caffe#27]
您好，我想请问一下当训练完CombinedMargin_spherenet36_E_model.prototxt之后，得到的模型特别大，若想要得到deploy.caffemodel，应该怎么样对其进行裁剪才能把innerproduct去掉，使网络变小。

**Comment by gehaocool** [comment]
Use 'deploy.prototxt' to load a net in caffe, the extra params in train_result.caffemodel will be ignored. Then save the net's parameters to deploy.caffemodel.

**Comment by Gincoeng** [comment]
thank you  so much
