### ISSUE TITLE
Can you share your alignment codes to align 112x96 resolution face images?

### ISSUE THREAD

**Issue by bongnamkang** [gehaocool/CombinedMargin-caffe#28]
I'd like to test your model in my project.
Can you share your alignment codes to align 112x96 resolution face images?

**Comment by gehaocool** [comment]
alignment code is the same as sphereface, use MTCNN to do detection and alignment
please refer to sphereface's code [face_detect_demo](https://github.com/wy1iu/sphereface/blob/master/preprocess/code/face_detect_demo.m)和[face_align_demo](https://github.com/wy1iu/sphereface/blob/master/preprocess/code/face_align_demo.m)
other version of MTCNN may also wok，but make sure use the same alignment method
