### ISSUE TITLE
caffe cpu单线程下C++调用耗时长

### ISSUE THREAD

**Issue by xisi789** [gehaocool/CombinedMargin-caffe#29]
不知您是否方便放出完整的训练好的模型（不是test版本，包含最后一个全连接层fc6_l2）。
我在测试中注意到您放出的模型，跟我自己按照您的方法训练得到的模型在intel caffe + cpu +单线程下C++调用耗时分别为500ms和80ms，觉得很奇怪。
或者您对训练好的模型做过什么处理吗？

**Comment by gehaocool** [comment]
没太明白你的问题，是说我放出的模型快，你自己训练的慢吗？
我的模型没有做任何额外处理，就是训练时候保存的caffemodel
