### ISSUE TITLE
训练的model什么时候发布

### ISSUE THREAD

**Issue by 975150313** [gehaocool/CombinedMargin-caffe#3]
请问一下,训练的model什么时候发布

**Comment by 975150313** [comment]
caffe.proto是基于原版caffe还是 [ https://github.com/happynear/caffe-windows](url)

**Comment by gehaocool** [comment]
caffe各种版本应该都可以，建议用happynear的版本
我自己是在原始版本上修改的

**Comment by 975150313** [comment]
有没有测试的model
