### ISSUE TITLE
同一个人的人脸图像用作者发布的模型计算的相似度值是多少，判断同一个人的阈值怎么确定

### ISSUE THREAD

**Issue by liuzhonghuacd** [gehaocool/CombinedMargin-caffe#7]
您好，我用作者发布的模型，计算同一个人的人脸图像相似值是0.4-0.7之间，大部分在0.5左右，感觉好像不对，用别的模型能达到0.8以上。

**Comment by gehaocool** [comment]
https://github.com/gehaocool/CombinedMargin-caffe/issues/5#issuecomment-443616309
